services:
  server:
    image: yehor542/socket_messenger_server:latest
    env_file:
      - ./server_side/.env


  client:
    image: yehor542/socket_messenger_client:latest
    env_file:
      - ./client_side/.env
    depends_on:
      - server
    stdin_open: true #same as -it flags
    tty: true
    command: sleep infinity
