services:
  client1:
    build: ./client_side
    env_file:
      - ./client_side/.env

  client2:
    build: ./client_side
    env_file:
      - ./client_side/.env
  
  server:
    build: ./server_side
    env_file:
      - ./server_side/.env
