services:
  server:
    build: ./server_side
    env_file:
      - ./server_side/.env


  client:
    build: ./client_side
    env_file:
      - ./client_side/.env
    depends_on:
      - server
    stdin_open: true #same as -it flags
    tty: true
    command: sleep infinity
