services:
  client1:
    build: ./client_side
    env_file:
      - ./client_side/.env
    depends_on:
      - server

  client2:
    build: ./client_side
    env_file:
      - ./client_side/.env
    depends_on:
      - client1
  
  server:
    build: ./server_side
    env_file:
      - ./server_side/.env
